set_property IOSTANDARD LVCMOS33 [get_ports *]
set_property PACKAGE_PIN U18 [get_ports Reset]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN A14 [get_ports clkSPI]
set_property PACKAGE_PIN B16 [get_ports clrSPI]
set_property PACKAGE_PIN B15 [get_ports csSPI]
set_property PACKAGE_PIN A16 [get_ports dataSPI]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN P18 [get_ports pwm_out]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property PACKAGE_PIN J18 [get_ports {Blue[3]}]
set_property PACKAGE_PIN K18 [get_ports {Blue[2]}]
set_property PACKAGE_PIN L18 [get_ports {Blue[1]}]
set_property PACKAGE_PIN N18 [get_ports {Blue[0]}]
set_property PACKAGE_PIN D17 [get_ports {Green[3]}]
set_property PACKAGE_PIN G17 [get_ports {Green[2]}]
set_property PACKAGE_PIN H17 [get_ports {Green[1]}]
set_property PACKAGE_PIN J17 [get_ports {Green[0]}]
set_property PACKAGE_PIN N19 [get_ports {Red[3]}]
set_property PACKAGE_PIN J19 [get_ports {Red[2]}]
set_property PACKAGE_PIN H19 [get_ports {Red[1]}]
set_property PACKAGE_PIN G19 [get_ports {Red[0]}]
set_property PACKAGE_PIN L1 [get_ports {dataout[15]}]
set_property PACKAGE_PIN P1 [get_ports {dataout[14]}]
set_property PACKAGE_PIN N3 [get_ports {dataout[13]}]
set_property PACKAGE_PIN P3 [get_ports {dataout[12]}]
set_property PACKAGE_PIN U3 [get_ports {dataout[11]}]
set_property PACKAGE_PIN W3 [get_ports {dataout[10]}]
set_property PACKAGE_PIN V3 [get_ports {dataout[9]}]
set_property PACKAGE_PIN V13 [get_ports {dataout[8]}]
set_property PACKAGE_PIN V14 [get_ports {dataout[7]}]
set_property PACKAGE_PIN U14 [get_ports {dataout[6]}]
set_property PACKAGE_PIN U15 [get_ports {dataout[5]}]
set_property PACKAGE_PIN W18 [get_ports {dataout[4]}]
set_property PACKAGE_PIN V19 [get_ports {dataout[3]}]
set_property PACKAGE_PIN U19 [get_ports {dataout[2]}]
set_property PACKAGE_PIN E19 [get_ports {dataout[1]}]
set_property PACKAGE_PIN U16 [get_ports {dataout[0]}]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
